apiVersion: v1
kind: Service
metadata:
  name: { { include "devops-debug-tools.fullname" . } }
  labels: { { - include "devops-debug-tools.labels" . | nindent 4 } }
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector: { { - include "devops-debug-tools.selectorLabels" . | nindent 4 } }
